//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheese
    {
        public string CheeseID { get; set; }
        public string CheeseName { get; set; }
        public Nullable<System.DateTime> CheeseInputDate { get; set; }
        public string InputedBy { get; set; }
        public Nullable<System.DateTime> CheeseLifeTime { get; set; }
    }
}
