//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheeseEntities : DbContext
    {
        public CheeseEntities()
            : base("name=CheeseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cheese> Cheese { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DefectiveProduct> DefectiveProducts { get; set; }
        public virtual DbSet<DetailCustomer> DetailCustomers { get; set; }
        public virtual DbSet<DetailEmployee> DetailEmployees { get; set; }
        public virtual DbSet<DetailFinalGoodsReceipt> DetailFinalGoodsReceipts { get; set; }
        public virtual DbSet<DetailGoodsReceipt> DetailGoodsReceipts { get; set; }
        public virtual DbSet<DetailGoodsReceiptCheck> DetailGoodsReceiptChecks { get; set; }
        public virtual DbSet<DetailSalesTransaction> DetailSalesTransactions { get; set; }
        public virtual DbSet<DetailSuppliesTransaction> DetailSuppliesTransactions { get; set; }
        public virtual DbSet<DetailWarehouse> DetailWarehouses { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FinalGoodsReceipt> FinalGoodsReceipts { get; set; }
        public virtual DbSet<GoodsReceipt> GoodsReceipts { get; set; }
        public virtual DbSet<GoodsReceiptCheck> GoodsReceiptChecks { get; set; }
        public virtual DbSet<Milk> Milk { get; set; }
        public virtual DbSet<OutgoingReport> OutgoingReports { get; set; }
        public virtual DbSet<SalesTransaction> SalesTransactions { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<SuppliesTransaction> SuppliesTransactions { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VerifiedInvoice> VerifiedInvoices { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<SalesInvoice> SalesInvoices { get; set; }
    }
}
