//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSalesTransaction
    {
        public string SalesTransactionID { get; set; }
        public string CheeseID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ItemPrice { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    }
}
