//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceiptCheck
    {
        public string GoodsReceiptCheckID { get; set; }
        public string GoodsReceiptID { get; set; }
        public Nullable<System.DateTime> GoodsReceiptCheckDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
