//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceipt
    {
        public string GoodsReceiptID { get; set; }
        public string SuppliesTransactionID { get; set; }
        public Nullable<System.DateTime> GoodsReceiptDate { get; set; }
        public string GoodsReceiptDescription { get; set; }
        public string CreatedBy { get; set; }
    }
}
