//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milk
    {
        public string MilkID { get; set; }
        public string MilkName { get; set; }
        public Nullable<System.DateTime> MilkInputDate { get; set; }
        public string InputBy { get; set; }
        public Nullable<System.DateTime> MilkLifeTime { get; set; }
    }
}
