//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutgoingReport
    {
        public string OutgoingReportID { get; set; }
        public string SalesTransactionID { get; set; }
        public string ScheduleID { get; set; }
        public string CheckStatus { get; set; }
        public string DeliveryStatus { get; set; }
        public string PackedBy { get; set; }
        public string ShippedBy { get; set; }
        public string OutgoingReportDescription { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
    }
}
