//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string ScheduleID { get; set; }
        public string SalesTransactionID { get; set; }
        public Nullable<int> BatchNumberSchedule { get; set; }
        public Nullable<System.DateTime> PackingDate { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public string ScheduleStatus { get; set; }
    }
}
