//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliesTransaction
    {
        public string SuppliesTransactionID { get; set; }
        public Nullable<System.DateTime> SuppliesTransactionDate { get; set; }
        public string SuppliesTransactionStatus { get; set; }
        public string SuppliesTransactionDescription { get; set; }
        public string RequestBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
