//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public string VendorID { get; set; }
        public string VendorName { get; set; }
        public Nullable<System.DateTime> VendorRegisterDate { get; set; }
        public string VendorRegisterBy { get; set; }
    }
}
