//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheese_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerifiedInvoice
    {
        public string VerifiedInvoiceID { get; set; }
        public string FinalGoodsReceiptID { get; set; }
        public string SuppliesTransactionID { get; set; }
        public Nullable<System.DateTime> VerifiedInvoiceDate { get; set; }
        public string CreatedBy { get; set; }
        public string VerifiedInvoiceStatus { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string PaidBy { get; set; }
        public Nullable<System.DateTime> PaidConfirmationDate { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    }
}
